### ISSUE TITLE
No support Greek characters 

### ISSUE THREAD

**Issue by compkos** [deldersveld/rDataTable#1]
Hello
rDataTable not support Greek characters (nvarchar columns sql server)
Thanks

**Comment by Rhein10** [comment]
Hello David, thanks for this awesome custom visual! 
1. Unfortunately the German "Umlaute"-Characters (Ä,ä,Ö,ö,Ü,ü) are not supported yet; any idea how to solve this problem?
2. Would it be possible to integrate a print function to this custom visual and / or export to R-Studio (R-Markup)?

**Comment by deldersveld** [comment]
Thank you both for the input. Work is needed to support unicode characters.

As for the print and export capabilities, the R package allows for a few buttons such as CSV, Print, etc. as outlined here: https://rstudio.github.io/DT/extensions.html When I implement the code, buttons do not appear. I believe that it is a Power BI custom visual sandbox issue outside of my control since the code runs fine standalone in R, but I would really like to build that export capability in. Support for exporting to R markdown is not available though.

**Comment by deldersveld** [comment]
Packaged version 1.1.0, which corrects the utf-8 issue
